server:
  port: 8080

spring:
  profiles:
    active: dev
  #循环依赖
#  main:
#    allow-circular-references: true
  datasource:
    driver-class-name: ${crazy.datasource.driver-class-name}
    url: jdbc:mysql://${crazy.datasource.host}:${crazy.datasource.port}/${crazy.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${crazy.datasource.username}
    password: ${crazy.datasource.password}
    # 需要用这种方式指定连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: ${crazy.redis.host}
      port: ${crazy.redis.port}
      password: ${crazy.redis.password}
      database: ${crazy.redis.database}

mybatis:
  # mapper配置文件，实现@Mapper的自动扫描和管理，需引入 mybatis-spring-boot-starter 依赖
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.crazy.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      crazy:
        mapper: debug
        service: info
        controller: info
        handler: debug

crazy:
  jwt:
    # jwt签名加密时使用的密钥（使用HS256需确保密钥大于等于256bits）
    admin-secret-key: crazytakeoutCRAZYTAKEOUTadminuse
    # jwt过期时间
    admin-ttl: 7200000
    # 前端传递过来的令牌名称
    admin-token-name: token
  # 腾讯云对象存储
  qcos:
    region: ${crazy.qcos.region}
    access-secret-id: ${crazy.qcos.access-secret-id}
    access-secret-key: ${crazy.qcos.access-secret-key}
    bucket-name: ${crazy.qcos.bucket-name}

springdoc:
  api-docs:
    path: /v3/api-docs # 全局 API 文档路径
  packages-to-scan: com.crazy.controller # 需要扫描的基础包，用于全局 API 文档生成
  group-configs:
    - group: admin
      paths-to-match:
        - /admin/**
      packages-to-scan:
        - com.crazy.controller.admin # admin 组中包含的包
    - group: user
      paths-to-match:
        - /user/**
      packages-to-scan:
        - com.crazy.controller.user # user 组中包含的包